language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - travis_retry composer install

script:
  - composer test-coverage
  - composer cs-check

after_success:
  - travis_retry vendor/bin/php-coveralls --verbose
