language: php

matrix:
  include:
  - php: 7.2
    env: CODE_COVERAGE=true
  - php: 7.3
  - php: 7.4snapshot
  - php: nightly

  allow_failures:
  - php: nightly

install:
  - travis_retry composer install

script:
  - composer test-coverage
  - composer static-analysis
  - composer cs-check

after_success:
  - |
    if [[ CODE_COVERAGE == true ]]; then
      travis_retry vendor/bin/php-coveralls --verbose
    fi
